version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xms1024m -Xmx2048m -XX:MaxHeapSize=512M -XX:+UseG1GC
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "gradle/dependencies.gradle" }}
      - run:
          name: Run Build
          command: ./gradlew build --console=plain
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_artifacts:
          path: build/outputs/apk
          destination: apk
      - save_cache:
          paths:
            - $HOME/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "gradle/dependencies.gradle" }}
