_free_space: &free_space
  name: Free space
  command: ./gradlew --stop

version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
                      -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -XX:ParallelGCThreads=1
                      -Djava.util.concurrent.ForkJoinPool.common.parallelism=1"
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: app-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle/versions.gradle" }}
      - run:
          name: Create Licences
          command: echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/android-sdk-license &&
            echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
      - run:
          name: Create Secrets
          command: .circleci/create_secrets.sh

      - run:
          name: Run static code analysis
          command: ./gradlew detekt ktlintCheck -Dorg.gradle.parallel=false -Pkotlin.incremental=false
            -Dkotlin.compiler.execution.strategy="in-process" --max-workers 1
            --console=plain --stacktrace
      - run:
          <<: *free_space
      - run:
          name: Assemble debug
          command: ./gradlew assembleDebug -Dorg.gradle.parallel=false -Pkotlin.incremental=false
            -Dkotlin.compiler.execution.strategy="in-process" --max-workers 1
            --console=plain --stacktrace
      - run:
          <<: *free_space
      - run:
          name: Assemble logRelease
          command: ./gradlew assembleLogRelease -Dorg.gradle.parallel=false -Pkotlin.incremental=false
            -Dkotlin.compiler.execution.strategy="in-process" --max-workers 1
            --console=plain --stacktrace
      - run:
          <<: *free_space
      - run:
          name: Assemble release
          command: ./gradlew assembleRelease -Dorg.gradle.parallel=false -Pkotlin.incremental=false
            -Dkotlin.compiler.execution.strategy="in-process" --max-workers 1
            --console=plain --stacktrace
      - run:
          <<: *free_space
      - run:
          name: Run lint
          command: ./gradlew lint -Dorg.gradle.parallel=false -Pkotlin.incremental=false
            -Dkotlin.compiler.execution.strategy="in-process" --max-workers 1
            --console=plain --stacktrace
      - run:
          <<: *free_space
      - run:
          name: Run tests
          command: ./gradlew test -Dorg.gradle.parallel=false -Pkotlin.incremental=false
            -Dkotlin.compiler.execution.strategy="in-process" --max-workers 1
            --console=plain --stacktrace
      - run:
          <<: *free_space
      - run:
          name: Build and Bundle
          command: ./gradlew build bundle -x lint -Dorg.gradle.parallel=false -Pkotlin.incremental=false
            -Dkotlin.compiler.execution.strategy="in-process" --max-workers 1
            --console=plain --stacktrace
      - run:
          <<: *free_space

      - store_artifacts:
          path: build/reports
          destination: reports
      - store_artifacts:
          path: build/outputs
          destination: outputs
      - save_cache:
          paths:
            - ~/.gradle
          key: app-{{ checksum  ".circleci/config.yml" }}-{{ checksum "gradle/versions.gradle" }}
      - persist_to_workspace:
          root: ~/app
          paths:
            - .circleci
            - ./build/outputs/apk/logRelease

  publish:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.2.1
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Publish in Telegram Group
          command: .circleci/publish_to_telegram.sh

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
