version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      _JAVA_OPTIONS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "gradle/dependencies.gradle" }}
      - run:
          name: Run Build
          command: ./gradlew build --console=plain
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_artifacts:
          path: build/outputs/apk
          destination: apk
      - save_cache:
          paths:
            - $HOME/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "gradle/dependencies.gradle" }}
