failFast: true

comments:
  UndocumentedPublicClass:
    searchInNestedClass: false
    searchInInnerClass: false
    searchInInnerObject: false
    searchInInnerInterface: false
  UndocumentedPublicFunction:
    active: false

complexity:
  NestedBlockDepth:
    active: false
  LongParameterList:
    active: false
  LargeClass:
    active: false
  ComplexMethod:
    active: false
  TooManyFunctions:
    active: false
  ComplexCondition:
    active: false
  StringLiteralDuplication:
    threshold: 5

exceptions:
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionMaxLength:
    maximumFunctionNameLength: 35

potential-bugs:
  UnsafeCast:
    active: false

style:
  MagicNumber:
    active: false
  ExpressionBodySyntax:
    active: false
