failFast: true

potential-bugs:
  UnsafeCast:
    active: false

complexity:
  StringLiteralDuplication:
    threshold: 5
  LongParameterList:
    active: false
  LargeClass:
    active: false
  TooManyFunctions:
    active: false
  ComplexCondition:
    active: false
  NestedBlockDepth:
    active: false

style:
  FunctionMaxLength:
    maximumFunctionNameLength: 35
  VariableMinLength:
    minimumVariableNameLength: 2
  VariableMaxLength:
    maximumVariableNameLength: 35
  MagicNumber:
    active: false
  DataClassContainsFunctions:
    active: false
  UseDataClass:
    active: false

comments:
  UndocumentedPublicClass:
    searchInNestedClass: false
    searchInInnerClass: false
    searchInInnerObject: false
    searchInInnerInterface: false
  UndocumentedPublicFunction:
    active: false
