failFast: true

potential-bugs:
  UnsafeCast:
    active: false

complexity:
  LongParameterList:
    active: false
  LargeClass:
    active: false
  ComplexMethod:
    active: false
  TooManyFunctions:
    active: false
  ComplexCondition:
    active: false
  NestedBlockDepth:
    active: false
  StringLiteralDuplication:
    threshold: 5

style:
  SafeCast:
    active: false
  FunctionMaxLength:
    active: false
  MagicNumber:
    active: false
  VariableMinLength:
    minimumVariableNameLength: 2
  VariableMaxLength:
    active: false
  DataClassContainsFunctions:
    active: false
  UseDataClass:
    active: false

comments:
  UndocumentedPublicClass:
    searchInNestedClass: false
    searchInInnerClass: false
    searchInInnerObject: false
    searchInInnerInterface: false
  UndocumentedPublicFunction:
    active: false
