failFast: true

comments:
  UndocumentedPublicClass:
    searchInInnerClass: false
    searchInInnerInterface: false
    searchInInnerObject: false
    searchInNestedClass: false
  UndocumentedPublicFunction:
    active: false

complexity:
  ComplexCondition:
    active: false
  ComplexMethod:
    active: false
  LabeledExpression:
    active: false
  LargeClass:
    active: false
  LongParameterList:
    active: false
  NestedBlockDepth:
    active: false
  StringLiteralDuplication:
      active: false
  TooManyFunctions:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionMaxLength:
    maximumFunctionNameLength: 35

performance:
  SpreadOperator:
    active: false

potential-bugs:
  UnsafeCast:
    active: false

style:
  ExpressionBodySyntax:
    active: false
  ForbiddenComment:
    active: true
    values: 'FIXME:,STOPSHIP:'
  MagicNumber:
    active: false
  UnusedPrivateMember:
    active: false
